# main workflow to run on code for checking
name: ci

# run on every commit to master and on every PR and subsequent commit on the PR
on:
  push:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/main.yml'
      - 'scripts/ci/**'
  release:
    types: [created, published, edited]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  APP_PATH: ${{ github.workspace }}/app

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  code-formatting:
    name: code formatting
    runs-on: ubuntu-20.04
    steps:
      - name: checkout app
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          path: ${{ env.APP_PATH }}

      - name: check code formatting
        id: check-code-format
        shell: bash
        run: |
          cd $APP_PATH
          python ./scripts/ci/run-clang-format.py -r .

  spell-check:
    name: spell checker
    runs-on: ubuntu-20.04

    steps:
      - name: checkout app
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DK_CI_TOKEN }}
          submodules: 'recursive'
          path: ${{ env.APP_PATH }}

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: install cSpell
        id: install-cspell
        shell: bash
        run: npm install -g cspell

      - name: spell checking
        id: spell-checking
        working-directory: ${{ env.APP_PATH }}
        shell: bash
        run: cspell "**/*.{c,h,md}"


